const mongoose = require('mongoose');

const NodeSchema = new mongoose.Schema({
  id: { type: String, required: true }, // ID generated by React Flow
  type: { type: String, required: true }, // e.g., 'factory', 'warehouse'
  position: {
    x: { type: Number, required: true },
    y: { type: Number, required: true }
  },
  data: {
    label: { type: String },
    maxCapacity: { type: Number, default: 100 },
    processingRate: { type: Number, default: 10 },
    currentLoad: { type: Number, default: 0 }
  }
});

const EdgeSchema = new mongoose.Schema({
  id: { type: String, required: true },
  source: { type: String, required: true }, // source node ID
  target: { type: String, required: true }, // target node ID
  animated: { type: Boolean, default: false },
  data: {
    maxFlow: { type: Number, default: 20 },
    currentFlow: { type: Number, default: 0 }
  }
});

const ProjectSchema = new mongoose.Schema({
  userId: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'User' 
    // Commented out 'required: true' just for early testing
  },
  name: { type: String, required: true },
  description: { type: String },
  nodes: [NodeSchema],
  edges: [EdgeSchema],
}, { timestamps: true });

module.exports = mongoose.model('Project', ProjectSchema);